local: true
port: 8080

elastic_config:
  url: http://localhost:9200
  index_name: embeddings-live
  
triton_config:
  url: http://localhost:8001

inference_config:
  models:
    SCENE:
      name: dinov3-vitb16
      precision: FP16
      input_name: images
      input_shape: [3, 224, 224]
      output_name: output
      output_shape: [768]
      batch_max_size: 16
      batch_max_queue_delay: 1000
      batch_preferred_sizes: [4, 8, 16]
    
    OBJECTS:
      name: dinov3-vitb16
      precision: FP16
      input_name: images
      input_shape: [3, 224, 224]
      output_name: output
      output_shape: [768]
      batch_max_size: 16
      batch_max_queue_delay: 1000
      batch_preferred_sizes: [4, 8, 16]
      
  instances:
    default: 1
    custom:
      "NVIDIA RTX A6000":
        SCENE: 10
        OBJECTS: 10
      "NVIDIA GeForce RTX 4070":
        SCENE: 5
        OBJECTS: 5

search_config:
  LIGHT:
    output_vectors: 10
    num_candidates: 50
    centriod_visit_percentage: 2
    vector_oversample_multiplier: 1.5
  MEDIUM:
    output_vectors: 10
    num_candidates: 200
    centriod_visit_percentage: 10
    vector_oversample_multiplier: 4
  HEAVY:
    output_vectors: 10
    num_candidates: 1000
    centriod_visit_percentage: 50
    vector_oversample_multiplier: 10