local: true

sources_config:
  ids: [1]
  default:
    inf_frame: 1
    conf_threshold: 0.01
    nms_iou_threshold: 0.5

elastic_config:
  url: http://localhost:9200
  index_name: embeddings-live
  
triton_config:
  url: http://localhost:8001

inference_config:
  task: Embedding
  models:
    YOLO:
      name: yolov9-e
      precision: FP16
      input_name: images
      input_shape: [3, 640, 640]
      output_name: output
      output_shape: [84, 8400]
      batch_max_size: 16
      batch_max_queue_delay: 2500
      batch_preferred_sizes: [2,4,6,8]

    DINO:
      name: dinov3-vitb16
      precision: FP16
      input_name: images
      input_shape: [3, 512, 512]
      output_name: output
      output_shape: [768]
      batch_max_size: 16
      batch_max_queue_delay: 1000
      batch_preferred_sizes: [4, 8, 16]

    DINO_OBJECTS:
      name: dinov3-bboxes
      precision: FP16
      input_name: images
      input_shape: [3, 224, 224]
      output_name: output
      output_shape: [768]
      batch_max_size: 16
      batch_max_queue_delay: 1000
      batch_preferred_sizes: [4, 8, 16]